// This file was autogenerated by ../closure-library-git/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../seditor4/scripts/app.js', ['seditor.app'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'goog.fx.DragDrop', 'goog.fx.DragDropGroup', 'goog.object', 'goog.ui.Component.EventType', 'goog.ui.Dialog', 'goog.ui.PopupMenu', 'goog.ui.Tab', 'goog.ui.TabBar', 'goog.ui.TabPane']);
